package model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class is the base model class for a transaction object
 */
public class Transaction {

    /**
     * Transaction ID is auto-generated by a counter in the service
     */
    private long id;

    /**
     * Placeholder to store the transaction amount
     */
    private BigDecimal amount;

    /**
     * Placeholder for the source account ID of transfer
     */
    private long fromAccountId;

    /**
     * Placeholder for the destination account ID of transfer
     */
    private long toAccountId;

    /**
     * Placeholder to save the timestamp of the transaction
     */
    private Date timestamp;

    public Transaction(long id, BigDecimal amount, long fromAccountId, long toAccountId) {
        this.id = id;
        this.fromAccountId = fromAccountId;
        this.toAccountId = toAccountId;
        this.amount = amount;
        this.timestamp = new Date();
    }
}
